name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Empfohlen: LTS-Version
      - uses: stefanoeb/jest-action@1.0.4
        with:
          args: "--testPathIgnorePatterns='selenium\\.test\\.js'"

