name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Empfohlen: LTS-Version
      - name: Install Python
        run: sudo apt-get install -y python3
      - uses: stefanoeb/jest-action@master
        with:
          args: "--testPathIgnorePatterns='selenium\\.test\\.js'"

